Template/Controllers/Feature_BoxesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Template.Models;

namespace Template.Controllers
{
    public class Feature_BoxesController : Controller
    {
        private TemplateFevralEntities db = new TemplateFevralEntities();

        // GET: Feature_Boxes
        public ActionResult Index()
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            return View(db.Feature_Boxes.ToList());
        }

        // GET: Feature_Boxes/Details/5
        public ActionResult Details(int? id)
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feature_Boxes feature_Boxes = db.Feature_Boxes.Find(id);
            if (feature_Boxes == null)
            {
                return HttpNotFound();
            }
            return View(feature_Boxes);
        }

        // GET: Feature_Boxes/Create
        public ActionResult Create()
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Feature_Boxes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "feature_boxes_id,feature_boxes_title,feature_boxes_icon,feature_boxes_content,feature_boxes_url")] Feature_Boxes feature_Boxes)
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                db.Feature_Boxes.Add(feature_Boxes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(feature_Boxes);
        }

        // GET: Feature_Boxes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feature_Boxes feature_Boxes = db.Feature_Boxes.Find(id);
            if (feature_Boxes == null)
            {
                return HttpNotFound();
            }
            return View(feature_Boxes);
        }

        // POST: Feature_Boxes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "feature_boxes_id,feature_boxes_title,feature_boxes_icon,feature_boxes_content,feature_boxes_url")] Feature_Boxes feature_Boxes)
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                db.Entry(feature_Boxes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feature_Boxes);
        }

        // GET: Feature_Boxes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feature_Boxes feature_Boxes = db.Feature_Boxes.Find(id);
            if (feature_Boxes == null)
            {
                return HttpNotFound();
            }
            return View(feature_Boxes);
        }

        // POST: Feature_Boxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!Check_Admin())
            {
                return RedirectToAction("Index", "Login");
            }
            Feature_Boxes feature_Boxes = db.Feature_Boxes.Find(id);
            db.Feature_Boxes.Remove(feature_Boxes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool Check_Admin()
        {

            if (Session["User_Name"] != null)
            {

                return true;
            }
            else
            {

                return false;
            }
        }
    }
}

Template/Views/Feature_Boxes/Create.cshtml
@model Template.Models.Feature_Boxes

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Feature_Boxes", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Feature_Boxes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_icon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_icon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_icon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Template/Views/Feature_Boxes/Delete.cshtml
@model Template.Models.Feature_Boxes

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Feature_Boxes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_icon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_icon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_url)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Template/Views/Feature_Boxes/Details.cshtml
@model Template.Models.Feature_Boxes

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Feature_Boxes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_icon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_icon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.feature_boxes_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.feature_boxes_url)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.feature_boxes_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Template/Views/Feature_Boxes/Edit.cshtml
@model Template.Models.Feature_Boxes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Feature_Boxes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.feature_boxes_id)

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_icon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_icon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_icon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.feature_boxes_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.feature_boxes_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.feature_boxes_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Template/Views/Feature_Boxes/Index.cshtml
@model IEnumerable<Template.Models.Feature_Boxes>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.feature_boxes_title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.feature_boxes_icon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.feature_boxes_content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.feature_boxes_url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.feature_boxes_title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.feature_boxes_icon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.feature_boxes_content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.feature_boxes_url)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.feature_boxes_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.feature_boxes_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.feature_boxes_id })
        </td>
    </tr>
}

</table>